// Phase 3 cleanup: moved static content constants out of App.js.

export const INTERVIEW_QUESTIONS = {
  no: [
    'Fortell litt om deg selv.',
    'Hvorfor søker du denne jobben?',
    'Hva er dine største styrker?',
    'Hva vil du si er dine utviklingsområder?',
    'Fortell om en gang du løste et vanskelig problem.',
    'Hvordan håndterer du stress og høyt tempo?',
    'Hvordan liker du å jobbe i team?',
    'Hva motiverer deg i hverdagen?',
    'Hvor ser du deg selv om 2–3 år?',
    'Har du noen spørsmål til oss?',
  ],
  en: [
    'Tell me about yourself.',
    'Why do you want this job?',
    'What are your biggest strengths?',
    'What would you like to improve?',
    'Tell me about a time you solved a difficult problem.',
    'How do you handle stress and high workload?',
    'How do you like working in a team?',
    'What motivates you day to day?',
    'Where do you see yourself in 2–3 years?',
    'Do you have any questions for us?',
  ],
};

export const CAREER_TIPS = {
  no: [
    'Skriv søknaden for arbeidsgiveren, ikke for deg selv. Vis hva du kan bidra med.',
    'Bruk tall når du kan: «behandlet 40–60 henvendelser per dag» slår «jobbet i kundeservice».',
    'Start CV-punkter med verb: «Planla», «koordinerte», «leverte», «forbedret».',
    'Skreddersy overskriften i CV-en til rollen du søker, ikke bare «CV».',
    'Bytt ut generelle ord («ansvarsfull») med konkrete eksempler og resultater.',
    'Hold deg til 3–6 punkt per jobb: velg det som er mest relevant for stillingen.',
    'Legg inn søkeord fra annonsen i CV-en (på en naturlig måte).',
    'Skriv kort om «hull i CV» før arbeidsgiver spør – 1–2 linjer er nok.',
    'Har du lite erfaring? Fremhev ansvar i skole/prosjekt/frivillig arbeid og overførbare ferdigheter.',
    'Kutt fyllord. Kortere setninger gjør teksten mer profesjonell.',
    'Sørg for at e-post og telefon er synlig og riktig (test å ringe deg selv).',
    'Be en venn lese søknaden: én runde med korrektur løfter helhetsinntrykket mye.',
  ],
  en: [
    'Write for the employer, not for yourself. Show what you can contribute.',
    'Use numbers when possible: “handled 40–60 requests/day” beats “customer service experience”.',
    'Start CV bullets with action verbs: “Built”, “Improved”, “Delivered”, “Coordinated”.',
    'Tailor your CV headline to the role you apply for, not just “Resume”.',
    'Replace generic words (“hard-working”) with concrete examples and outcomes.',
    'Keep 3–6 bullets per job and focus on what’s most relevant to the position.',
    'Add keywords from the job ad to your CV (naturally).',
    'Explain employment gaps briefly before you’re asked — 1–2 lines is enough.',
    'New to the field? Highlight transferable skills from school/projects/volunteering.',
    'Cut filler words. Shorter sentences read more professional.',
    'Make sure your email and phone are correct and easy to find.',
    'Ask someone to proofread — one quick review improves the overall impression a lot.',
  ],
  vi: [
    'Viết đơn xin việc cho nhà tuyển dụng, không phải cho bản thân bạn. Cho họ thấy bạn có thể đóng góp gì.',
    'Dùng số liệu khi có thể: «xử lý 40–60 yêu cầu mỗi ngày» ấn tượng hơn «đã làm dịch vụ khách hàng».',
    'Bắt đầu các gạch đầu dòng trong CV bằng động từ: «Lên kế hoạch», «Điều phối», «Bàn giao», «Cải thiện».',
    'Điều chỉnh tiêu đề CV theo đúng vị trí bạn ứng tuyển, đừng chỉ ghi «CV».',
    'Thay các từ chung chung («có trách nhiệm») bằng ví dụ cụ thể và kết quả thực tế.',
    'Giữ 3–6 gạch đầu dòng cho mỗi công việc: chọn những gì liên quan nhất đến vị trí ứng tuyển.',
    'Đưa từ khóa từ tin tuyển dụng vào CV (một cách tự nhiên).',
    'Giải thích ngắn gọn về «khoảng trống trong CV» trước khi nhà tuyển dụng hỏi – 1–2 dòng là đủ.',
    'Ít kinh nghiệm? Hãy làm nổi bật trách nhiệm từ trường học/dự án/công việc tình nguyện và các kỹ năng có thể chuyển đổi.',
    'Cắt bỏ từ thừa. Câu ngắn gọn khiến văn bản chuyên nghiệp hơn.',
    'Đảm bảo email và số điện thoại hiển thị rõ ràng và chính xác (thử gọi cho chính mình để kiểm tra).',
    'Nhờ một người bạn đọc đơn xin việc: một lượt kiểm tra có thể cải thiện đáng kể ấn tượng tổng thể.',
  ],
  pl: [
    'Pisz podanie z myślą o pracodawcy, nie o sobie. Pokaż, co możesz wnieść.',
    'Używaj liczb, gdy to możliwe: «obsługiwałem 40–60 zapytań dziennie» brzmi lepiej niż «pracowałem w obsłudze klienta».',
    'Zaczynaj punkty w CV od czasowników: «Planowałem», «koordynowałem», «dostarczałem», «usprawniłem».',
    'Dostosuj nagłówek CV do stanowiska, na które aplikujesz, a nie tylko «CV».',
    'Zamień ogólniki (np. «odpowiedzialny») na konkretne przykłady i wyniki.',
    'Trzymaj się 3–6 punktów na stanowisko: wybierz to, co najbardziej istotne dla oferty.',
    'Wpleć słowa kluczowe z ogłoszenia do CV (w naturalny sposób).',
    'Krótko wyjaśnij «luki w CV», zanim zapyta o to pracodawca – wystarczą 1–2 linijki.',
    'Masz mało doświadczenia? Podkreśl obowiązki ze szkoły/projektów/wolontariatu oraz umiejętności, które można przenieść.',
    'Usuń zbędne słowa. Krótsze zdania sprawiają, że tekst wygląda bardziej profesjonalnie.',
    'Upewnij się, że e-mail i telefon są widoczne i poprawne (przetestuj, dzwoniąc do siebie).',
    'Poproś znajomego o przeczytanie podania: jedna korekta znacznie poprawia ogólne wrażenie.',
  ],
  lt: [
    'Rašyk prašymą darbdaviui, o ne sau. Parodyk, ką gali prisidėti.',
    'Naudok skaičius, kai gali: «per dieną apdorojau 40–60 užklausų» skamba geriau nei «dirbau klientų aptarnavime».',
    'Pradėk CV punktus veiksmažodžiais: «Planavau», «koordinavau», «pristačiau», «patobulinau».',
    'Pritaikyk CV antraštę pareigoms, į kurias kreipiesi, o ne rašyk tik «CV».',
    'Pakeisk bendrus žodžius (pvz., «atsakingas») konkrečiais pavyzdžiais ir rezultatais.',
    'Laikykis 3–6 punktų kiekvienam darbui: rink tai, kas aktualiausia pareigoms.',
    'Įtrauk raktažodžius iš skelbimo į CV (natūraliai).',
    'Trumpai paaiškink «CV spragas» prieš darbdaviui paklausus – užtenka 1–2 eilučių.',
    'Turi mažai patirties? Pabrėžk atsakomybę iš mokyklos/projektų/savanorystės ir perkeliamus įgūdžius.',
    'Atsisakyk nereikalingų žodžių. Trumpesni sakiniai atrodo profesionaliau.',
    'Pasirūpink, kad el. paštas ir telefonas būtų matomi ir teisingi (patikrink, paskambindamas sau).',
    'Paprašyk draugo perskaityti prašymą: viena korektūra gerokai pagerina bendrą įspūdį.',
  ],
  ar: [
    'اكتب طلب التوظيف من أجل صاحب العمل، وليس من أجل نفسك. أظهر ما يمكنك تقديمه.',
    'استخدم الأرقام كلما أمكن: «تعاملت مع 40-60 طلبًا يوميًا» أفضل من «عملت في خدمة العملاء».',
    'ابدأ نقاط السيرة الذاتية بأفعال: «خططت»، «نسّقت»، «سلّمت»، «حسّنت».',
    'خصّص عنوان السيرة الذاتية للوظيفة التي تتقدم لها، وليس مجرد «السيرة الذاتية».',
    'استبدل الكلمات العامة (مثل «مسؤول») بأمثلة ونتائج ملموسة.',
    'التزم بـ 3-6 نقاط لكل وظيفة: اختر الأكثر صلة بالمنصب.',
    'أدرج الكلمات المفتاحية من الإعلان في السيرة الذاتية (بشكل طبيعي).',
    'اشرح باختصار «الفجوات في السيرة الذاتية» قبل أن يسأل صاحب العمل – سطر أو سطران يكفيان.',
    'خبرتك قليلة؟ أبرز المسؤوليات من المدرسة/المشاريع/العمل التطوعي والمهارات القابلة للنقل.',
    'احذف الكلمات الزائدة. الجمل الأقصر تجعل النص أكثر احترافية.',
    'تأكد من ظهور البريد الإلكتروني ورقم الهاتف بوضوح وصحة (جرّب الاتصال بنفسك للتأكد).',
    'اطلب من صديق قراءة الطلب: مراجعة واحدة تحسّن الانطباع العام كثيرًا.',
  ],
  so: [
    'U qor codsiga shaqo-bixiyaha, ma aha adiga. Tus waxa aad ku biirin karto.',
    'Isticmaal tirooyin markaad awoodo: «waxaan maareeyay 40–60 codsi maalintii» ayaa ka fiican «waxaan ka shaqeeyay adeegga macaamiisha».',
    'Ku bilow qodobbada CV-ga falal: «Waxaan qorsheeyay», «isku duway», «keenay», «hagaajiyay».',
    'U habee cinwaanka CV-ga jagada aad codsanayso, hana ku qorin oo kaliya «CV».',
    'Bedel erayada guud (sida «mas\'uul») aad ka bedesho tusaalayaal iyo natiijooyin dhab ah.',
    'Ku joogso 3–6 qodob shaqo kasta: dooro kuwa ugu habboon jagada.',
    'Ku dar erayada furaha ah ee xayeysiiska CV-ga (si dabiici ah).',
    'Si kooban u sharax «boosaska CV-ga» ka hor inta shaqo-bixiyuhu weydiin – 1–2 xariiqood ayaa ku filan.',
    'Khibrad yar ayaad haysaa? Xoojii mas\'uuliyadaha dugsiga/mashaariicda/shaqada tabaruca ah iyo xirfadaha la wareejin karo.',
    'Ka saar erayada aan lama huraanka ahayn. Weedho gaagaaban ayaa qoraalka ka dhigaya mid xirfadeed.',
    'Hubi in iimeelka iyo telefoonka ay muuqdaan si sax ah (isku day inaad naftaada wacdo).',
    'Waydii saaxiib inuu akhriyo codsiga: hal jeer oo la saxo ayaa aad u kordhiya aragtida guud.',
  ],
};
