// Phase 4 cleanup: moved static option arrays out of App.js.

export const schoolOptions = [
  'Universitetet i Oslo',
  'NTNU',
  'Universitetet i Bergen',
  'Universitetet i Tromsø',
  'Universitetet i Agder',
  'Universitetet i Stavanger',
  'Universitetet i Sørøst-Norge',
  'NMBU',
  'OsloMet – storbyuniversitetet',
  'Nord universitet',
  'Høgskulen på Vestlandet',
  'Høgskolen i Innlandet',
  'Høgskolen i Østfold',
  'Høgskolen i Molde',
  'Høgskolen i Volda',
  'BI Norwegian Business School',
  'Høyskolen Kristiania',
  'NLA Høgskolen',
  'MF vitenskapelig høyskole',
  'Westerdals Oslo ACT',
  'Norges idrettshøgskole',
  'Kunsthøgskolen i Oslo',
  'Arkitektur- og designhøgskolen i Oslo',
  'Fagskole - Teknikk og industriell produksjon',
  'Fagskole - Helse og oppvekst',
  'Fagskole - IT og digitalisering',
  'Ullern videregående skole',
  'Elvebakken videregående skole',
  'Nydalen videregående skole',
  'Frogner videregående skole',
  'Bygdøy videregående skole',
  'Bjørkelangen videregående skole',
  'Bergen katedralskole',
  'Strinda videregående skole',
  'Åsane videregående skole',
  'Drammen videregående skole',
  'Kirkeparken videregående skole',
  'St. Olav videregående skole',
  'Lillestrøm videregående skole',
  'Skedsmo videregående skole',
  'Romerike videregående skole',
  'Annen skole',
];

export const languageOptions = [
  'Norsk',
  'Engelsk',
  'Svensk',
  'Dansk',
  'Finsk',
  'Islandsk',
  'Tysk',
  'Nederlandsk',
  'Fransk',
  'Spansk',
  'Italiensk',
  'Portugisisk',
  'Russisk',
  'Ukrainsk',
  'Rumensk',
  'Bulgarsk',
  'Gresk',
  'Tsjekkisk',
  'Ungarsk',
  'Kinesisk',
  'Japansk',
  'Koreansk',
  'Arabisk',
  'Hebraisk',
  'Hindi',
  'Punjabi',
  'Urdu',
  'Tyrkisk',
  'Persisk (Farsi)',
  'Thai',
  'Vietnamesisk',
  'Polsk',
];
