import { StyleSheet } from 'react-native';
import { THEME } from './theme';

export const styles = StyleSheet.create({
  container: {
    flex: 1,
    backgroundColor: '#F7F5F0',
  },
  scrollContent: {
    padding: 20,
    paddingBottom: 120,
  },
  heroHeader: {
    // (ikke i bruk på Home lenger – beholdes for enkel rollback)
    backgroundColor: '#0f2147',
    borderRadius: 28,
    padding: 22,
    marginBottom: 18,
    flexDirection: 'row',
    alignItems: 'center',
  },
  heroTextWrapper: {
    flex: 1,
  },
  brandRow: {
    flexDirection: 'row',
    alignItems: 'center',
    marginBottom: 18,
  },
  brandName: {
    fontSize: 18,
    fontWeight: '700',
    color: '#dbeafe',
  },
  notificationBadge: {
    marginLeft: 10,
    paddingHorizontal: 10,
    height: 24,
    borderRadius: 12,
    backgroundColor: '#2dd4bf',
    justifyContent: 'center',
    alignItems: 'center',
  },
  notificationCount: {
    color: THEME.colors.text,
    fontWeight: '800',
    fontSize: 12,
  },
  heroTitle: {
    fontSize: 28,
    fontWeight: '800',
    color: '#fff',
    marginBottom: 8,
  },
  heroSubtitle: {
    fontSize: 15,
    color: '#cbd5e1',
    lineHeight: 22,
    marginBottom: 18,
    maxWidth: '90%',
  },
  progressSection: {
    marginTop: 8,
  },
  progressLabelRow: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    marginBottom: 10,
  },
  progressLabel: {
    color: '#cbd5e1',
    fontSize: 13,
  },
  progressPercent: {
    color: '#34d399',
    fontSize: 13,
    fontWeight: '700',
  },
  progressBar: {
    width: '100%',
    height: 10,
    borderRadius: 24,
    backgroundColor: '#152848',
  },
  progressFill: {
    width: '68%',
    height: '100%',
    borderRadius: 24,
    backgroundColor: '#34d399',
  },
  profileImage: {
    width: 100,
    height: 100,
    borderRadius: 24,
    marginLeft: 16,
  },
  mainCard: {
    backgroundColor: THEME.colors.surface,
    borderRadius: 16,
    padding: 20,
    marginBottom: 16,

    // Material-ish card elevation
    shadowColor: '#000',
    shadowOpacity: 0.14,
    shadowRadius: 8,
    shadowOffset: { width: 0, height: 4 },
    elevation: 2,
  },
  cardTitle: {
    fontSize: 20,
    fontWeight: '800',
    marginBottom: 10,
    color: THEME.colors.text,
  },
  cardText: {
    fontSize: 15,
    color: THEME.colors.muted,
    lineHeight: 22,
    marginBottom: 18,
  },
  cardButton: {
    backgroundColor: THEME.colors.primary,
    paddingVertical: 14,
    paddingHorizontal: 16,
    minHeight: 48,
    borderRadius: 12,
    alignItems: 'center',
    justifyContent: 'center',

    // Material-ish elevation
    shadowColor: '#000',
    shadowOpacity: 0.18,
    shadowRadius: 6,
    shadowOffset: { width: 0, height: 3 },
    elevation: 3,
  },
  cardButtonText: {
    color: '#fff',
    fontSize: 15,
    fontWeight: '700',
    letterSpacing: 0.3,
  },
  sectionTitle: {
    fontSize: 18,
    fontWeight: '800',
    color: THEME.colors.text,
    marginBottom: 14,
  },
  actionGrid: {
    flexDirection: 'row',
    flexWrap: 'wrap',
    justifyContent: 'space-between',
    marginBottom: 20,
  },
  actionItem: {
    width: '48%',
    borderRadius: 16,
    padding: 16,
    marginBottom: 14,

    // Material-ish elevation (subtle)
    shadowColor: '#000',
    shadowOpacity: 0.10,
    shadowRadius: 6,
    shadowOffset: { width: 0, height: 3 },
    elevation: 1,
  },
  actionIcon: {
    fontSize: 24,
    marginBottom: 12,
  },
  actionTitle: {
    fontSize: 15,
    fontWeight: '700',
    color: THEME.colors.text,
    marginBottom: 6,
  },
  actionSubtitle: {
    fontSize: 13,
    color: THEME.colors.muted,
    lineHeight: 20,
  },
  progressCard: {
    backgroundColor: THEME.colors.surface,
    borderRadius: 16,
    padding: 16,
    marginBottom: 14,

    // Material-ish card elevation
    shadowColor: '#000',
    shadowOpacity: 0.10,
    shadowRadius: 6,
    shadowOffset: { width: 0, height: 3 },
    elevation: 1,
  },
  progressHeader: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    marginBottom: 12,
  },
  progressCardTitle: {
    fontSize: 15,
    fontWeight: '800',
    color: THEME.colors.text,
  },
  progressCardPercent: {
    fontSize: 15,
    fontWeight: '800',
    color: THEME.colors.success,
  },
  progressOuter: {
    width: '100%',
    height: 10,
    borderRadius: 12,
    backgroundColor: THEME.colors.border,
  },
  progressInner: {
    height: '100%',
    borderRadius: 12,
    backgroundColor: THEME.colors.primary,
  },
  progressStatus: {
    marginTop: 10,
    color: THEME.colors.muted,
    fontSize: 13,
  },
  tipCard: {
    backgroundColor: THEME.colors.primarySoft,
    borderRadius: THEME.radius.card,
    padding: 16,
    marginBottom: 20,
    borderWidth: 1,
    borderColor: THEME.colors.border,
  },
  tipTitle: {
    fontSize: 16,
    fontWeight: '800',
    color: THEME.colors.text,
    marginBottom: 10,
  },
  tipText: {
    fontSize: 14,
    color: THEME.colors.muted,
    lineHeight: 20,
  },
  tipLink: {
    marginTop: 14,
  },
  tipLinkText: {
    color: THEME.colors.primary,
    fontWeight: '800',
  },
  pageCard: {
    backgroundColor: '#FFFFFF',
    borderRadius: 16,
    padding: 20,
    marginBottom: 16,
    shadowColor: '#000',
    shadowOpacity: 0.08,
    shadowRadius: 12,
    shadowOffset: { width: 0, height: 2 },
    elevation: 3,
  },
  pageTitle: {
    fontSize: 20,
    fontWeight: '600',
    color: '#1a1a1a',
    marginBottom: 6,
  },
  pageSubtitle: {
    fontSize: 14,
    color: '#888888',
    marginBottom: 18,
  },
  inputLabel: {
    fontSize: 12,
    fontWeight: '500',
    color: '#555555',
    marginBottom: 6,
  },
  input: {
    backgroundColor: '#FAFAFA',
    borderRadius: 10,
    paddingVertical: 12,
    paddingHorizontal: 14,
    borderWidth: 1.5,
    borderColor: '#e8e8e8',
    fontSize: 15,
    color: '#1a1a1a',
    marginBottom: 14,
  },
  inputText: {
    color: THEME.colors.text,
    fontSize: 15,
  },
  placeholderText: {
    color: '#71717a',
    fontSize: 15,
  },
  helpText: {
    color: THEME.colors.muted,
    fontSize: 13,
    marginBottom: 8,
  },
  listItem: {
    backgroundColor: THEME.colors.surface,
    borderRadius: 16,
    padding: 14,
    marginBottom: 14,
    borderWidth: 1,
    borderColor: THEME.colors.border,
  },
  inlineRow: {
    flexDirection: 'row',
    justifyContent: 'space-between',
  },
  inlineInput: {
    flex: 1,
    marginRight: 8,
  },
  removeButton: {
    backgroundColor: THEME.colors.surface,
    paddingVertical: 10,
    paddingHorizontal: 14,
    minHeight: 44,
    borderRadius: THEME.radius.control,
    alignItems: 'center',
    justifyContent: 'center',
    marginTop: 6,
    borderWidth: 1,
    borderColor: THEME.colors.danger,
  },
  removeButtonText: {
    color: THEME.colors.danger,
    fontWeight: '800',
    letterSpacing: 0.25,
  },
  smallButton: {
    backgroundColor: THEME.colors.surfaceAlt,
    paddingVertical: 10,
    paddingHorizontal: 14,
    minHeight: 44,
    borderRadius: THEME.radius.control,
    alignItems: 'center',
    justifyContent: 'center',
    marginTop: 4,
    marginBottom: 16,
    borderWidth: 1,
    borderColor: THEME.colors.border,
  },
  smallButtonText: {
    color: THEME.colors.primary,
    fontWeight: '700',
    letterSpacing: 0.25,
  },
  dropdownList: {
    backgroundColor: THEME.colors.surface,
    borderWidth: 1,
    borderColor: THEME.colors.border,
    borderRadius: 12,
    marginBottom: 14,
    overflow: 'hidden',

    // Material-ish elevation
    shadowColor: '#000',
    shadowOpacity: 0.10,
    shadowRadius: 6,
    shadowOffset: { width: 0, height: 3 },
    elevation: 2,
  },
  dropdownItem: {
    paddingVertical: 12,
    paddingHorizontal: 16,
  },
  dropdownItemText: {
    color: THEME.colors.text,
    fontSize: 15,
  },
  dropdownItemSub: {
    marginTop: 2,
    color: THEME.colors.muted,
    fontSize: 12,
  },
  filterChipRow: {
    flexDirection: 'row',
    flexWrap: 'wrap',
    paddingHorizontal: 8,
    paddingBottom: 10,
  },
  filterChip: {
    backgroundColor: THEME.colors.surfaceAlt,
    borderWidth: 1,
    borderColor: THEME.colors.border,
    paddingVertical: 8,
    paddingHorizontal: 12,
    borderRadius: THEME.radius.pill,
    marginRight: 8,
    marginBottom: 8,
  },
  filterChipActive: {
    backgroundColor: THEME.colors.primary,
    borderColor: THEME.colors.primary,
  },
  filterChipText: {
    color: THEME.colors.text,
    fontSize: 13,
    fontWeight: '800',
  },
  filterChipTextActive: {
    color: '#fff',
  },
  textArea: {
    minHeight: 100,
    textAlignVertical: 'top',
  },
  primaryButton: {
    backgroundColor: '#E8501A',
    paddingVertical: 14,
    paddingHorizontal: 24,
    minHeight: 48,
    borderRadius: 12,
    alignItems: 'center',
    justifyContent: 'center',
    marginTop: 8,
    shadowColor: '#E8501A',
    shadowOpacity: 0.25,
    shadowRadius: 12,
    shadowOffset: { width: 0, height: 4 },
    elevation: 4,
  },
  primaryButtonText: {
    color: '#fff',
    fontSize: 15,
    fontWeight: '600',
    letterSpacing: 0.2,
  },
  secondaryButton: {
    backgroundColor: '#FFFFFF',
    paddingVertical: 12,
    paddingHorizontal: 24,
    minHeight: 48,
    borderRadius: 12,
    alignItems: 'center',
    justifyContent: 'center',
    marginTop: 12,
    borderWidth: 1.5,
    borderColor: '#e0e0e0',
    elevation: 0,
  },
  secondaryButtonText: {
    color: '#1a1a1a',
    fontSize: 15,
    fontWeight: '500',
    letterSpacing: 0.1,
  },
  analysisCard: {
    backgroundColor: THEME.colors.surface,
    borderRadius: 16,
    padding: 16,
    marginTop: 16,
    borderWidth: 1,
    borderColor: THEME.colors.border,

    // Material-ish elevation
    shadowColor: '#000',
    shadowOpacity: 0.08,
    shadowRadius: 6,
    shadowOffset: { width: 0, height: 3 },
    elevation: 1,
  },
  analysisHeading: {
    fontSize: 16,
    fontWeight: '700',
    marginBottom: 14,
    color: THEME.colors.text,
  },
  analysisRow: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    marginBottom: 10,
  },
  analysisLabel: {
    fontSize: 14,
    color: THEME.colors.muted,
  },
  analysisValue: {
    fontSize: 14,
    fontWeight: '700',
    color: THEME.colors.text,
  },
  analysisSubheading: {
    fontSize: 14,
    fontWeight: '700',
    marginTop: 12,
    marginBottom: 8,
    color: THEME.colors.text,
  },
  analysisList: {
    fontSize: 14,
    color: THEME.colors.muted,
    marginBottom: 6,
    lineHeight: 20,
  },
  summaryCard: {
    backgroundColor: THEME.colors.surface,
    borderRadius: 16,
    padding: 16,
    borderWidth: 1,
    borderColor: THEME.colors.border,
    marginBottom: 16,

    // Material-ish elevation
    shadowColor: '#000',
    shadowOpacity: 0.08,
    shadowRadius: 6,
    shadowOffset: { width: 0, height: 3 },
    elevation: 1,
  },
  summaryName: {
    fontSize: 18,
    fontWeight: '700',
    color: THEME.colors.text,
    marginBottom: 6,
  },
  summaryText: {
    fontSize: 14,
    color: THEME.colors.muted,
    lineHeight: 20,
  },
  messageCard: {
    backgroundColor: THEME.colors.surface,
    borderRadius: 16,
    padding: 16,
    marginBottom: 14,

    // Material-ish elevation
    shadowColor: '#000',
    shadowOpacity: 0.10,
    shadowRadius: 6,
    shadowOffset: { width: 0, height: 3 },
    elevation: 1,
  },
  messageTitle: {
    fontSize: 16,
    fontWeight: '700',
    marginBottom: 8,
    color: THEME.colors.text,
  },
  messageText: {
    fontSize: 14,
    color: THEME.colors.muted,
    lineHeight: 20,
  },

  tableCard: {
    marginTop: 14,
    backgroundColor: THEME.colors.surface,
    borderRadius: 16,
    borderWidth: 1,
    borderColor: THEME.colors.border,
    overflow: 'hidden',

    // Material-ish elevation
    shadowColor: '#000',
    shadowOpacity: 0.10,
    shadowRadius: 6,
    shadowOffset: { width: 0, height: 3 },
    elevation: 1,
  },
  tableHeaderRow: {
    flexDirection: 'row',
    alignItems: 'center',
    paddingVertical: 10,
    paddingHorizontal: 12,
    backgroundColor: THEME.colors.surfaceAlt,
    borderBottomWidth: 1,
    borderBottomColor: THEME.colors.border,
  },
  tableHeaderCell: {
    width: 56,
    textAlign: 'center',
    fontSize: 12,
    fontWeight: '800',
    color: THEME.colors.muted,
  },
  tableJobHeader: {
    flex: 1,
    width: 'auto',
    textAlign: 'left',
  },
  tableRow: {
    flexDirection: 'row',
    alignItems: 'center',
    paddingVertical: 12,
    paddingHorizontal: 12,
    borderBottomWidth: 1,
    borderBottomColor: THEME.colors.border,
  },
  tableJobCell: {
    flex: 1,
    paddingRight: 10,
  },
  tableJobTitle: {
    fontSize: 14,
    fontWeight: '700',
    color: THEME.colors.text,
  },
  tableJobCompany: {
    marginTop: 2,
    fontSize: 12,
    color: THEME.colors.muted,
  },
  checkbox: {
    width: 34,
    height: 34,
    borderRadius: 10,
    borderWidth: 1,
    borderColor: THEME.colors.border,
    backgroundColor: THEME.colors.surface,
    alignItems: 'center',
    justifyContent: 'center',
    marginLeft: 10,
  },
  checkboxOn: {
    backgroundColor: THEME.colors.primary,
    borderColor: THEME.colors.primary,
  },
  checkboxText: {
    fontSize: 16,
    fontWeight: '900',
    color: THEME.colors.text,
  },
  checkboxTextOn: {
    color: '#ffffff',
  },

  // Applications (Ærlig. styling)
  aerligAppsTableCard: {
    marginTop: 14,
    backgroundColor: '#FFFFFF',
    borderRadius: 22,
    borderWidth: 1,
    borderColor: 'rgba(26, 26, 46, 0.12)',
    overflow: 'hidden',
  },
  aerligAppsTableHeaderRow: {
    flexDirection: 'row',
    alignItems: 'center',
    paddingVertical: 10,
    paddingHorizontal: 12,
    backgroundColor: 'rgba(26, 26, 46, 0.04)',
    borderBottomWidth: 1,
    borderBottomColor: 'rgba(26, 26, 46, 0.10)',
  },
  aerligAppsTableHeaderCell: {
    width: 56,
    textAlign: 'center',
    fontSize: 12,
    fontWeight: '900',
    color: 'rgba(26, 26, 46, 0.58)',
  },
  aerligAppsTableJobHeader: {
    flex: 1,
    width: 'auto',
    textAlign: 'left',
  },
  aerligAppsTableRow: {
    flexDirection: 'row',
    alignItems: 'center',
    paddingVertical: 12,
    paddingHorizontal: 12,
    borderBottomWidth: 1,
    borderBottomColor: 'rgba(26, 26, 46, 0.10)',
  },
  aerligAppsTableJobCell: {
    flex: 1,
    paddingRight: 10,
  },
  aerligAppsTableJobTitle: {
    fontSize: 14,
    fontWeight: '900',
    color: '#1A1A2E',
  },
  aerligAppsTableJobCompany: {
    marginTop: 2,
    fontSize: 12,
    fontWeight: '800',
    color: 'rgba(26, 26, 46, 0.66)',
  },
  aerligAppsCheckbox: {
    width: 34,
    height: 34,
    borderRadius: 10,
    borderWidth: 1,
    borderColor: 'rgba(26, 26, 46, 0.20)',
    backgroundColor: '#FFFFFF',
    alignItems: 'center',
    justifyContent: 'center',
    marginLeft: 10,
  },
  aerligAppsCheckboxOn: {
    backgroundColor: '#E8622A',
    borderColor: '#E8622A',
  },
  aerligAppsCheckboxText: {
    fontSize: 16,
    fontWeight: '900',
    color: '#1A1A2E',
  },
  aerligAppsCheckboxTextOn: {
    color: '#FFFFFF',
  },

  profileField: {
    marginBottom: 16,
  },
  bottomBar: {
    position: 'absolute',
    left: 0,
    right: 0,
    bottom: 0,
    height: 88,
    paddingHorizontal: 16,
    paddingTop: 10,
    paddingBottom: 14,

    backgroundColor: '#FFFFFF',
    borderTopWidth: 1,
    borderTopColor: '#f0f0f0',

    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-around',

    shadowColor: '#000',
    shadowOpacity: 0.06,
    shadowRadius: 8,
    shadowOffset: { width: 0, height: -2 },
    elevation: 8,
  },
  bottomButton: {
    alignItems: 'center',
    justifyContent: 'center',
    flex: 1,
    paddingVertical: 6,
    borderRadius: 16,
  },
  bottomIcon: {
    fontSize: 20,
    color: '#aaaaaa',
  },

  // Home (new)
  homeTopBar: {
    backgroundColor: THEME.colors.surface,
    borderRadius: THEME.radius.card,
    padding: 18,
    marginBottom: 16,
    minHeight: 134,
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',

    // Material-ish elevation
    shadowColor: '#000',
    shadowOpacity: 0.14,
    shadowRadius: 10,
    shadowOffset: { width: 0, height: 4 },
    elevation: 3,
  },
  homeTopBarLeft: {
    flex: 1,
    paddingRight: 10,
  },
  homeBrandRow: {
    flexDirection: 'row',
    alignItems: 'center',
    marginBottom: 10,
  },
  homeBrandName: {
    fontSize: 14,
    fontWeight: '800',
    color: THEME.colors.muted,
  },
  homeGreeting: {
    fontSize: 22,
    fontWeight: '900',
    color: THEME.colors.text,
    marginBottom: 6,
  },
  homeTagline: {
    fontSize: 15,
    fontWeight: '800',
    color: THEME.colors.text,
    marginBottom: 8,
  },
  homeSub: {
    color: THEME.colors.muted,
    fontSize: 14,
    lineHeight: 20,
  },
  homeMascotButton: {
    width: 86,
    height: 86,
    borderRadius: 28,
    overflow: 'hidden',
    backgroundColor: THEME.colors.surfaceAlt,
    borderWidth: 1,
    borderColor: THEME.colors.border,
    alignItems: 'center',
    justifyContent: 'center',
  },
  mascotStage: {
    width: '100%',
    height: '100%',
    alignItems: 'center',
    justifyContent: 'center',
  },
  mascotShadow: {
    position: 'absolute',
    bottom: 16,
    width: 44,
    height: 10,
    borderRadius: 999,
    backgroundColor: '#000',
  },
  mascotWrap: {
    width: 86,
    height: 86,
    alignItems: 'center',
    justifyContent: 'center',
  },
  mascotHead: {
    position: 'absolute',
    top: 16,
    width: 44,
    height: 44,
    borderRadius: 22,
    backgroundColor: '#f1c27d',
    borderWidth: 1,
    borderColor: THEME.colors.border,
    overflow: 'hidden',
  },
  mascotHair: {
    position: 'absolute',
    top: 0,
    left: 0,
    right: 0,
    height: 16,
    backgroundColor: '#1f1b2e',
    borderTopLeftRadius: 22,
    borderTopRightRadius: 22,
  },
  mascotNeck: {
    position: 'absolute',
    top: 56,
    width: 14,
    height: 10,
    borderRadius: 6,
    backgroundColor: '#e0ac69',
    borderWidth: 1,
    borderColor: THEME.colors.border,
  },
  mascotBody: {
    position: 'absolute',
    top: 62,
    width: 54,
    height: 28,
    borderRadius: 16,
    backgroundColor: THEME.colors.primarySoft,
    borderWidth: 1,
    borderColor: THEME.colors.border,
  },
  mascotArmWave: {
    position: 'absolute',
    right: 8,
    top: 66,
    width: 26,
    height: 8,
    borderRadius: 8,
    backgroundColor: '#f1c27d',
    borderWidth: 1,
    borderColor: THEME.colors.border,
  },
  mascotArmStatic: {
    position: 'absolute',
    left: 10,
    top: 70,
    width: 22,
    height: 8,
    borderRadius: 8,
    backgroundColor: '#f1c27d',
    borderWidth: 1,
    borderColor: THEME.colors.border,
    opacity: 0.85,
  },
  mascotHand: {
    position: 'absolute',
    right: 4,
    top: 63,
    width: 10,
    height: 10,
    borderRadius: 5,
    backgroundColor: '#f1c27d',
    borderWidth: 1,
    borderColor: THEME.colors.border,
  },
  mascotEyesRow: {
    position: 'absolute',
    top: 34,
    flexDirection: 'row',
  },
  mascotEye: {
    width: 6,
    height: 6,
    borderRadius: 3,
    backgroundColor: THEME.colors.background,
    marginRight: 10,
  },
  mascotMouth: {
    position: 'absolute',
    top: 46,
    width: 14,
    height: 4,
    borderRadius: 2,
    backgroundColor: THEME.colors.border,
  },
  homePrimaryRow: {
    flexDirection: 'row',
    alignItems: 'center',
  },
  actionList: {
    marginBottom: 18,
  },
  actionRow: {
    backgroundColor: THEME.colors.surface,
    borderRadius: THEME.radius.card,
    paddingVertical: 14,
    paddingHorizontal: 14,
    borderWidth: 1,
    borderColor: THEME.colors.border,
    marginBottom: 10,

    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',

    // Material-ish elevation (subtle)
    shadowColor: '#000',
    shadowOpacity: 0.08,
    shadowRadius: 6,
    shadowOffset: { width: 0, height: 3 },
    elevation: 1,
  },
  actionRowLeft: {
    flexDirection: 'row',
    alignItems: 'center',
    flex: 1,
    paddingRight: 10,
  },
  actionIconPill: {
    width: 44,
    height: 44,
    borderRadius: 12,
    alignItems: 'center',
    justifyContent: 'center',
    marginRight: 12,
  },
  actionRowText: {
    flex: 1,
  },
  actionRowTitle: {
    fontSize: 15,
    fontWeight: '800',
    color: THEME.colors.text,
    marginBottom: 2,
  },
  actionRowSubtitle: {
    color: THEME.colors.muted,
    fontSize: 13,
    lineHeight: 18,
  },
  actionChevron: {
    color: '#a1a1aa',
    fontSize: 22,
    fontWeight: '900',
    marginLeft: 8,
  },
  progressList: {
    marginBottom: 12,
  },
  progressRow: {
    backgroundColor: THEME.colors.surface,
    borderRadius: THEME.radius.card,
    padding: 16,
    borderWidth: 1,
    borderColor: THEME.colors.border,
    marginBottom: 10,

    // Material-ish elevation (subtle)
    shadowColor: '#000',
    shadowOpacity: 0.08,
    shadowRadius: 6,
    shadowOffset: { width: 0, height: 3 },
    elevation: 1,
  },
  bottomIconActive: {
    color: '#E8622A',
  },
  bottomLabel: {
    fontSize: 11,
    color: '#aaaaaa',
    marginTop: 4,
    fontWeight: '600',
    letterSpacing: 0.1,
  },
  bottomLabelActive: {
    color: '#E8501A',
  },
  fabButton: {
    width: 68,
    height: 68,
    borderRadius: 34,
    backgroundColor: THEME.colors.primary,
    alignItems: 'center',
    justifyContent: 'center',
    marginBottom: 18,
    shadowColor: '#000',
    shadowOpacity: 0.24,
    shadowRadius: 10,
    shadowOffset: { width: 0, height: 4 },
    elevation: 6,
  },
  fabIcon: {
    color: '#ffffff',
    fontSize: 32,
    lineHeight: 34,
    fontWeight: '700',
  },

  // Home (Ærlig. minimal dashboard)
  aerligHomeWrap: {
    marginHorizontal: -20,
    marginTop: -20,
    paddingHorizontal: 20,
    paddingTop: 20,
    paddingBottom: 20,
    backgroundColor: '#F7F5F0',
  },
  aerligHeroCard: {
    backgroundColor: '#FFFFFF',
    borderRadius: 16,
    padding: 18,
    marginBottom: 14,
    shadowColor: '#000',
    shadowOpacity: 0.08,
    shadowRadius: 12,
    shadowOffset: { width: 0, height: 2 },
    elevation: 3,
  },
  aerligHeroHeader: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
    marginBottom: 14,
  },
  aerligLogo: {
    fontSize: 18,
    fontWeight: '900',
    color: '#1A1A2E',
    letterSpacing: 0.2,
  },
  aerligBadge: {
    minWidth: 30,
    height: 26,
    borderRadius: 13,
    paddingHorizontal: 10,
    alignItems: 'center',
    justifyContent: 'center',
    backgroundColor: 'rgba(232, 98, 42, 0.12)',
    borderWidth: 1,
    borderColor: 'rgba(232, 98, 42, 0.28)',
  },
  aerligBadgeText: {
    fontSize: 12,
    fontWeight: '900',
    color: '#E8622A',
  },
  aerligHeroGreeting: {
    fontSize: 22,
    fontWeight: '900',
    color: '#1A1A2E',
    marginBottom: 6,
  },
  aerligHeroSubtitle: {
    fontSize: 14,
    lineHeight: 20,
    color: 'rgba(26, 26, 46, 0.72)',
    marginBottom: 14,
  },
  aerligPrimaryButton: {
    backgroundColor: '#E8501A',
    paddingVertical: 14,
    paddingHorizontal: 24,
    minHeight: 50,
    borderRadius: 12,
    alignItems: 'center',
    justifyContent: 'center',
    shadowColor: '#E8501A',
    shadowOpacity: 0.25,
    shadowRadius: 12,
    shadowOffset: { width: 0, height: 4 },
    elevation: 4,
  },
  aerligPrimaryButtonText: {
    color: '#FFFFFF',
    fontSize: 15,
    fontWeight: '600',
    letterSpacing: 0.2,
  },
  aerligQuickRow: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    marginTop: 10,
  },
  aerligQuickButton: {
    flex: 1,
    backgroundColor: '#FFFFFF',
    borderRadius: 16,
    borderWidth: 1,
    borderColor: 'rgba(26, 26, 46, 0.14)',
    paddingVertical: 12,
    alignItems: 'center',
    justifyContent: 'center',
  },
  aerligQuickButtonText: {
    fontSize: 13,
    fontWeight: '900',
    color: '#1A1A2E',
  },
  aerligSecondaryButton: {
    marginTop: 12,
    backgroundColor: '#FFFFFF',
    paddingVertical: 12,
    paddingHorizontal: 24,
    minHeight: 48,
    borderRadius: 12,
    alignItems: 'center',
    justifyContent: 'center',
    borderWidth: 1.5,
    borderColor: '#e0e0e0',
  },
  aerligSecondaryButtonText: {
    color: '#1a1a1a',
    fontSize: 15,
    fontWeight: '500',
    letterSpacing: 0.1,
  },
  aerligCard: {
    backgroundColor: '#FFFFFF',
    borderRadius: 16,
    padding: 16,
    marginBottom: 14,
    shadowColor: '#000',
    shadowOpacity: 0.08,
    shadowRadius: 12,
    shadowOffset: { width: 0, height: 2 },
    elevation: 3,
  },
  aerligEmptyCard: {
    borderStyle: 'dashed',
  },
  aerligCardEyebrow: {
    fontSize: 12,
    fontWeight: '900',
    color: 'rgba(26, 26, 46, 0.58)',
    textTransform: 'uppercase',
    letterSpacing: 0.7,
    marginBottom: 8,
  },
  aerligCardTitle: {
    fontSize: 16,
    fontWeight: '900',
    color: '#1A1A2E',
    marginBottom: 2,
  },
  aerligCardMeta: {
    fontSize: 13,
    fontWeight: '800',
    color: 'rgba(26, 26, 46, 0.66)',
    marginBottom: 12,
  },
  aerligCardSectionTitle: {
    marginTop: 2,
    marginBottom: 6,
    fontSize: 12,
    fontWeight: '900',
    color: '#1A1A2E',
  },
  aerligCardBody: {
    fontSize: 13,
    lineHeight: 19,
    color: 'rgba(26, 26, 46, 0.76)',
  },
  aerligCardLink: {
    marginTop: 12,
    color: '#E8622A',
    fontSize: 13,
    fontWeight: '900',
  },
  aerligMeterRow: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
    marginBottom: 8,
  },
  aerligMeterLabel: {
    fontSize: 13,
    fontWeight: '900',
    color: '#1A1A2E',
  },
  aerligMeterValue: {
    fontSize: 13,
    fontWeight: '900',
    color: '#1A1A2E',
  },
  aerligMeterOuter: {
    height: 10,
    borderRadius: 999,
    backgroundColor: 'rgba(26, 26, 46, 0.10)',
    overflow: 'hidden',
    marginBottom: 10,
  },
  aerligMeterInner: {
    height: '100%',
    borderRadius: 999,
  },
  aerligMeterGood: {
    backgroundColor: '#16A34A',
  },
  aerligMeterWarn: {
    backgroundColor: '#D97706',
  },
  aerligMeterBad: {
    backgroundColor: '#DC2626',
  },
  aerligMeterStatus: {
    fontSize: 12,
    fontWeight: '500',
    marginTop: 2,
    marginBottom: 6,
  },
  aerligPill: {
    alignSelf: 'flex-start',
    paddingVertical: 6,
    paddingHorizontal: 10,
    borderRadius: 999,
    borderWidth: 1,
    marginBottom: 10,
  },
  aerligPillYes: {
    backgroundColor: 'rgba(58, 125, 68, 0.10)',
    borderColor: 'rgba(58, 125, 68, 0.35)',
  },
  aerligPillNo: {
    backgroundColor: 'rgba(232, 98, 42, 0.10)',
    borderColor: 'rgba(232, 98, 42, 0.35)',
  },
  aerligPillText: {
    fontSize: 12,
    fontWeight: '900',
  },
  aerligPillTextYes: {
    color: '#3A7D44',
  },
  aerligPillTextNo: {
    color: '#E8622A',
  },
  aerligGrid: {
    flexDirection: 'row',
    flexWrap: 'wrap',
    justifyContent: 'space-between',
  },
  aerligMiniCard: {
    width: '48%',
    backgroundColor: '#FFFFFF',
    borderRadius: 22,
    padding: 14,
    borderWidth: 1,
    borderColor: 'rgba(26, 26, 46, 0.12)',
    marginBottom: 14,
    minHeight: 116,
  },
  aerligMiniCardFull: {
    width: '100%',
    minHeight: 108,
  },
  aerligMiniLabel: {
    fontSize: 12,
    fontWeight: '900',
    color: 'rgba(26, 26, 46, 0.60)',
  },
  aerligMiniValue: {
    marginTop: 8,
    marginBottom: 6,
    fontSize: 28,
    fontWeight: '900',
    color: '#1A1A2E',
  },
  aerligMiniHint: {
    marginTop: 'auto',
    fontSize: 12,
    fontWeight: '900',
    color: '#E8622A',
  },
  aerligProfileRow: {
    flexDirection: 'row',
    alignItems: 'center',
  },
  aerligProfileValue: {
    marginTop: 8,
    marginBottom: 4,
    fontSize: 26,
    fontWeight: '900',
    color: '#1A1A2E',
  },
  aerligProfileHint: {
    fontSize: 12,
    fontWeight: '800',
    color: 'rgba(26, 26, 46, 0.66)',
    marginBottom: 10,
  },
  aerligProfileMeter: {
    height: 10,
    borderRadius: 999,
    backgroundColor: 'rgba(26, 26, 46, 0.10)',
    overflow: 'hidden',
  },
  aerligProfileMeterFill: {
    height: '100%',
    borderRadius: 999,
    backgroundColor: '#1A1A2E',
  },
  aerligTipCard: {
    backgroundColor: '#FEF0EB',
    borderRadius: 14,
    padding: 16,
    borderWidth: 0.5,
    borderColor: '#F5C4A0',
    marginBottom: 8,
  },
  aerligTipLabel: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 5,
    marginBottom: 6,
  },
  aerligTipLabelText: {
    fontSize: 11,
    fontWeight: '500',
    color: '#E8501A',
    letterSpacing: 0.4,
  },
  aerligTipTitle: {
    fontSize: 13,
    fontWeight: '900',
    color: '#1A1A2E',
    marginBottom: 8,
  },
  aerligTipText: {
    fontSize: 14,
    lineHeight: 22,
    color: '#7A2A0A',
    fontWeight: '400',
  },

  // Profile (Ærlig. styling)
  aerligPageCard: {
    backgroundColor: '#FFFFFF',
    borderRadius: 16,
    padding: 20,
    marginBottom: 14,
    shadowColor: '#000',
    shadowOpacity: 0.08,
    shadowRadius: 12,
    shadowOffset: { width: 0, height: 2 },
    elevation: 3,
  },
  aerligPageTitle: {
    fontSize: 20,
    fontWeight: '600',
    color: '#1a1a1a',
    marginBottom: 6,
  },
  aerligPageSubtitle: {
    fontSize: 14,
    lineHeight: 20,
    color: '#888888',
    marginBottom: 14,
  },
  aerligLabel: {
    color: 'rgba(26, 26, 46, 0.66)',
    fontWeight: '900',
  },
  aerligHelpText: {
    color: 'rgba(26, 26, 46, 0.70)',
  },
  aerligMessageText: {
    color: 'rgba(26, 26, 46, 0.76)',
    fontWeight: '800',
  },
  aerligInput: {
    backgroundColor: '#FAFAFA',
    borderColor: '#e8e8e8',
    borderRadius: 10,
    color: '#1a1a1a',
  },
  aerligInputText: {
    color: '#1A1A2E',
    fontSize: 15,
    fontWeight: '800',
  },
  aerligPlaceholderText: {
    color: 'rgba(26, 26, 46, 0.50)',
    fontSize: 15,
    fontWeight: '800',
  },
  aerligSmallButton: {
    backgroundColor: '#FFFFFF',
    borderColor: 'rgba(26, 26, 46, 0.16)',
    borderRadius: 16,
    marginBottom: 12,
  },
  aerligSmallButtonText: {
    color: '#1A1A2E',
    fontWeight: '900',
  },
  aerligRemoveButton: {
    borderRadius: 16,
  },
  aerligRemoveButtonText: {
    fontWeight: '900',
  },
  aerligDropdownList: {
    backgroundColor: '#FFFFFF',
    borderColor: 'rgba(26, 26, 46, 0.12)',
    borderRadius: 18,
  },
  aerligDropdownItemText: {
    color: '#1A1A2E',
    fontWeight: '800',
  },
  aerligDropdownItemSub: {
    color: 'rgba(26, 26, 46, 0.60)',
  },
  aerligFilterChipRow: {
    paddingHorizontal: 0,
  },
  aerligFilterChip: {
    backgroundColor: '#FFFFFF',
    borderColor: 'rgba(26, 26, 46, 0.16)',
  },
  aerligFilterChipActive: {
    backgroundColor: '#1A1A2E',
    borderColor: '#1A1A2E',
  },
  aerligFilterChipText: {
    color: '#1A1A2E',
    fontWeight: '900',
  },
  aerligFilterChipTextActive: {
    color: '#FFFFFF',
  },
  aerligCheckbox: {
    borderColor: 'rgba(26, 26, 46, 0.20)',
    backgroundColor: '#FFFFFF',
  },
  aerligCheckboxOn: {
    backgroundColor: '#1A1A2E',
    borderColor: '#1A1A2E',
  },
  aerligCheckboxText: {
    color: '#1A1A2E',
  },
  aerligCheckboxTextOn: {
    color: '#FFFFFF',
  },
  aerligInlineNote: {
    marginLeft: 10,
    color: 'rgba(26, 26, 46, 0.70)',
    fontSize: 13,
    fontWeight: '800',
  },
  aerligLinkText: {
    color: '#E8622A',
    fontWeight: '900',
  },
  autoSaveBar: {
    minHeight: 24,
    alignItems: 'center',
    justifyContent: 'center',
    marginTop: 12,
    marginBottom: 4,
  },
  autoSaveText: {
    fontSize: 13,
    color: '#6B7280',
  },

  cvModalOverlay: {
    flex: 1,
    backgroundColor: 'rgba(0,0,0,0.45)',
    justifyContent: 'center',
    alignItems: 'center',
    padding: 20,
  },
  cvModalCard: {
    backgroundColor: '#FFFFFF',
    borderRadius: 20,
    padding: 24,
    width: '100%',
    maxWidth: 420,
    shadowColor: '#000',
    shadowOpacity: 0.2,
    shadowRadius: 20,
    shadowOffset: { width: 0, height: 6 },
    elevation: 10,
  },
  cvModalTitle: {
    fontSize: 20,
    fontWeight: '700',
    color: '#111827',
    marginBottom: 4,
  },
  cvModalSubtitle: {
    fontSize: 14,
    color: '#6B7280',
    marginBottom: 16,
  },

  aerligDangerButton: {
    marginTop: 12,
    backgroundColor: '#FFFFFF',
    paddingVertical: 14,
    paddingHorizontal: 16,
    minHeight: 50,
    borderRadius: 16,
    alignItems: 'center',
    justifyContent: 'center',
    borderWidth: 1,
    borderColor: 'rgba(239, 68, 68, 0.55)',
  },
  aerligDangerButtonText: {
    color: THEME.colors.danger,
    fontSize: 15,
    fontWeight: '900',
    letterSpacing: 0.2,
  },

  // Analysis accents
  aerligAccentNavy: {
    borderLeftWidth: 4,
    borderLeftColor: '#1A1A2E',
    paddingLeft: 12,
  },
  aerligAccentOrange: {
    borderLeftWidth: 4,
    borderLeftColor: '#E8622A',
    paddingLeft: 12,
  },
  aerligAccentGreen: {
    borderLeftWidth: 4,
    borderLeftColor: '#3A7D44',
    paddingLeft: 12,
  },

  // Interview (Ærlig. chat-style)
  aerligChatBubble: {
    backgroundColor: '#FFFFFF',
    borderRadius: 22,
    padding: 14,
    borderWidth: 1,
    borderColor: 'rgba(26, 26, 46, 0.12)',
    marginBottom: 14,
  },
  aerligChatBubbleAi: {
    borderLeftWidth: 4,
    borderLeftColor: '#1A1A2E',
    paddingLeft: 12,
  },
  aerligChatBubbleUser: {
    borderLeftWidth: 4,
    borderLeftColor: '#E8622A',
    paddingLeft: 12,
  },
  aerligChatMetaRow: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
    marginBottom: 10,
  },
  aerligChatMetaRight: {
    fontSize: 12,
    fontWeight: '900',
    color: 'rgba(26, 26, 46, 0.60)',
  },
  aerligChatTag: {
    borderRadius: 999,
    paddingVertical: 6,
    paddingHorizontal: 10,
    borderWidth: 1,
  },
  aerligChatTagAi: {
    backgroundColor: 'rgba(26, 26, 46, 0.08)',
    borderColor: 'rgba(26, 26, 46, 0.18)',
  },
  aerligChatTagUser: {
    backgroundColor: 'rgba(232, 98, 42, 0.10)',
    borderColor: 'rgba(232, 98, 42, 0.22)',
  },
  aerligChatTagText: {
    fontSize: 12,
    fontWeight: '900',
  },
  aerligChatTagTextAi: {
    color: '#1A1A2E',
  },
  aerligChatTagTextUser: {
    color: '#E8622A',
  },
  aerligChatText: {
    fontSize: 15,
    lineHeight: 22,
    color: '#1A1A2E',
    fontWeight: '800',
  },
  aerligChatInput: {
    marginBottom: 0,
    marginTop: 0,
  },
  aerligChatControlsRow: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    marginBottom: 12,
  },

  // Back button (simple navigation cleanup)
  aerligBackButton: {
    alignSelf: 'flex-start',
    backgroundColor: '#F3F4F6',
    borderRadius: 10,
    paddingVertical: 8,
    paddingHorizontal: 16,
    marginBottom: 12,
    overflow: 'hidden',
  },
  aerligBackButtonText: {
    color: '#555555',
    fontSize: 14,
    fontWeight: '500',
  },

  // Profile list compaction (experience / education)
  aerligEntryHeader: {
    flexDirection: 'row',
    alignItems: 'flex-start',
    justifyContent: 'space-between',
    marginBottom: 10,
  },
  aerligEntryTitle: {
    fontSize: 14,
    fontWeight: '900',
    color: '#1A1A2E',
  },
  aerligEntrySub: {
    marginTop: 2,
    fontSize: 12,
    fontWeight: '800',
    color: 'rgba(26, 26, 46, 0.66)',
  },
  aerligEntryYears: {
    fontSize: 12,
    fontWeight: '900',
    color: 'rgba(26, 26, 46, 0.60)',
  },
  aerligEntryEditRow: {
    flexDirection: 'row',
    justifyContent: 'space-between',
  },
  aerligInputCompact: {
    paddingVertical: 10,
    marginBottom: 10,
  },
  aerligListRow: {
    backgroundColor: 'transparent',
    borderWidth: 0,
    borderRadius: 0,
    paddingVertical: 10,
    paddingHorizontal: 0,
    marginBottom: 8,
    borderBottomWidth: 1,
    borderBottomColor: 'rgba(26, 26, 46, 0.10)',
  },
  aerligListRowHeader: {
    marginBottom: 6,
  },
  aerligListRowRemoveButton: {
    marginTop: 2,
    minHeight: 40,
    paddingVertical: 8,
    borderRadius: 14,
  },
  aerligListRowRemoveButtonText: {
    fontSize: 13,
  },
  aerligRowActions: {
    flexDirection: 'row',
    marginTop: 4,
    marginBottom: 6,
  },
  aerligRowActionChip: {
    paddingVertical: 6,
    paddingHorizontal: 10,
    marginBottom: 0,
  },
  aerligRowActionChipDanger: {
    borderColor: 'rgba(239, 68, 68, 0.55)',
  },
  aerligRowActionTextDanger: {
    color: THEME.colors.danger,
  },

  // Variant C profile summary
  profileSummaryHeader: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 12,
    marginBottom: 16,
    marginTop: 8,
  },
  profileAvatar: {
    width: 52,
    height: 52,
    borderRadius: 14,
    backgroundColor: '#E8501A',
    alignItems: 'center',
    justifyContent: 'center',
    flexShrink: 0,
  },
  profileAvatarText: {
    color: '#FFFFFF',
    fontSize: 18,
    fontWeight: '500',
  },
  profileSummaryName: {
    fontSize: 16,
    fontWeight: '500',
    color: '#111827',
    marginBottom: 2,
  },
  profileSummaryStrengthLabel: {
    fontSize: 12,
    color: '#6B7280',
    marginBottom: 4,
  },
  profileStrengthTrack: {
    height: 6,
    borderRadius: 3,
    backgroundColor: '#E8E6E0',
    overflow: 'hidden',
  },
  profileStrengthFill: {
    height: 6,
    borderRadius: 3,
    backgroundColor: '#E8501A',
  },
  profileCardGrid: {
    flexDirection: 'row',
    flexWrap: 'wrap',
    gap: 12,
    marginBottom: 12,
  },
  profileCardRow: {
    flexDirection: 'row',
    gap: 12,
    marginBottom: 12,
  },
  profileSummaryCard: {
    backgroundColor: '#FFFFFF',
    borderRadius: 8,
    padding: 12,
    borderWidth: 0.5,
    borderColor: '#E8E6E0',
    flex: 1,
  },
  profileSummaryCardFull: {
    backgroundColor: '#FFFFFF',
    borderRadius: 8,
    padding: 12,
    borderWidth: 0.5,
    borderColor: '#E8E6E0',
  },
  profileCardIcon: {
    fontSize: 18,
    marginBottom: 4,
  },
  profileCardLabel: {
    fontSize: 11,
    color: '#6B7280',
    marginBottom: 2,
  },
  profileCardValue: {
    fontSize: 13,
    fontWeight: '500',
    color: '#111827',
  },
  profileSkillChip: {
    backgroundColor: '#FEF2EE',
    borderRadius: 20,
    paddingHorizontal: 10,
    paddingVertical: 4,
    borderWidth: 1,
    borderColor: '#FDDDD4',
  },
  profileSkillChipText: {
    fontSize: 12,
    color: '#E8501A',
    fontWeight: '500',
  },
  profileSkillChipExtra: {
    backgroundColor: '#F3F4F6',
    borderColor: '#E5E7EB',
  },
});
